In [4]:
from google.colab import files
uploaded = files.upload()

Saving exam_sample.csv to exam_sample.csv

In [5]:
import pandas as pd
import numpy as np
exam = pd.read_csv("./exam_sample.csv", encoding='utf-8')
exam.head

<bound method NDFrame.head of    student_no class  science  english  math sex
0           1     A       50       98    50   m
1           2     A       60       97    60   w
2           3     A       78       86    45   w
3           4     A       58       98    30   m
4           5     B       65       80    90   w
5           6     B       98       89    50   m
6           7     B       45       90    80   m
7           8     B       25       78    90   w
8           9     C       15       98    20   w
9          10     C       45       93    50   w>

In [7]:
df1 = exam.groupby(['class'])
df1
df1.get_group('A')

   student_no class  science  english  math sex
0           1     A       50       98    50   m
1           2     A       60       97    60   w
2           3     A       78       86    45   w
3           4     A       58       98    30   m

In [9]:
exam.groupby('class').mean()
df1.mean()

<ipython-input-9-fa1c3cc8aa18>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  exam.groupby('class').mean()
<ipython-input-9-fa1c3cc8aa18>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df1.mean()

       student_no  science  english   math
class
A             2.5    61.50    94.75  46.25
B             6.5    58.25    84.25  77.50
C             9.5    30.00    95.50  35.00

In [10]:
exam.groupby( [ 'class', 'sex' ] ).mean()

           student_no  science  english  math
class sex
A     m           2.5     54.0     98.0  40.0
      w           2.5     69.0     91.5  52.5
B     m           6.5     71.5     89.5  65.0
      w           6.5     45.0     79.0  90.0
C     w           9.5     30.0     95.5  35.0

In [11]:
exam['math'].groupby(exam['class']).mean()

class
A    46.25
B    77.50
C    35.00
Name: math, dtype: float64

In [13]:
exam.groupby('class')['math'].mean()

class
A    46.25
B    77.50
C    35.00
Name: math, dtype: float64

In [ ]:
# agg(새롭게 만들어낼 컬럼명 = )

exam.groupby('class').agg(  mean_math = ( 'math', 'mean' ) )

In [14]:
# 수학 평균 / 영어 중앙값 / 반별 학생수

exam.groupby('class').agg( mean_math = ('math','mean'),
                          median_english = ('english', 'median'),
                          n = ('class', 'count') )

       mean_math  median_english  n
class
A          46.25            97.5  4
B          77.50            84.5  4
C          35.00            95.5  2

In [15]:
exam.groupby('class').agg( [ 'mean', 'median', 'count'] )

<ipython-input-15-6803b9c2e8cf>:1: FutureWarning: ['sex'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  exam.groupby('class').agg( [ 'mean', 'median', 'count'] )

      student_no              science              english               \
            mean median count    mean median count    mean median count
class
A            2.5    2.5     4   61.50   59.0     4   94.75   97.5     4
B            6.5    6.5     4   58.25   55.0     4   84.25   84.5     4
C            9.5    9.5     2   30.00   30.0     2   95.50   95.5     2

        math
        mean median count
class
A      46.25   47.5     4
B      77.50   85.0     4
C      35.00   35.0     2

In [16]:
exam.groupby('class').agg({ 'math':['min','max'] , 'english':'mean'  } )

      math     english
       min max    mean
class
A       30  60   94.75
B       50  90   84.25
C       20  50   95.50

In [17]:
df1.apply(lambda x : x.mean() >= 50 )
df1.filter(lambda x : x.math.mean() >= 50 )

<ipython-input-17-2f5aa6475f30>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df1.apply(lambda x : x.mean() >= 50 )
<ipython-input-17-2f5aa6475f30>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df1.apply(lambda x : x.mean() >= 50 )
<ipython-input-17-2f5aa6475f30>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df1.apply(lambda x : x.mean() >= 50 )

   student_no class  science  english  math sex
4           5     B       65       80    90   w
5           6     B       98       89    50   m
6           7     B       45       90    80   m
7           8     B       25       78    90   w

In [20]:
from google.colab import files
uploaded = files.upload()

Saving mpg.csv to mpg (1).csv

In [23]:
import pandas as pd
import numpy as np
mpg = pd.read_csv("./mpg.csv", encoding='utf-8')

In [32]:
mpg.groupby('category')['cty'].mean().sort_values(ascending=False)
mpg.groupby('category').agg( mean_cty = ('cty', 'mean') ).sort_values('mean_cty', ascending=False)


mpg.groupby('manufacturer')['hwy'].mean().sort_values(ascending=False).head(3)
mpg.groupby('manufacturer').agg( mean_hwy = ('hwy', 'mean') ).sort_values('mean_hwy', ascending=False).head(3)

mpg[ mpg.category == 'compact'].groupby('manufacturer').agg(n=('manufacturer','count')).sort_values('n', ascending=False)
mpg[ mpg.category == 'compact'].value_counts('manufacturer')

manufacturer
audi          15
volkswagen    14
toyota        12
subaru         4
nissan         2
dtype: int64